"""Initial tables

Revision ID: 2620b63b3fb9
Revises: 
Create Date: 2019-03-23 23:14:30.505362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2620b63b3fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=5), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('len', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
