"""add title_v2

Revision ID: 482a52fcba58
Revises: 2620b63b3fb9
Create Date: 2019-03-25 22:07:03.701675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482a52fcba58'
down_revision = '2620b63b3fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title_v2', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title_v2')
    # ### end Alembic commands ###
