"""Initial tables

Revision ID: 917fa6e1d8a7
Revises: 
Create Date: 2019-03-23 22:38:21.859323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '917fa6e1d8a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=40), nullable=True),
        sa.Column('owner_id', sa.String(length=5), nullable=True),
        sa.Column('date_created', postgresql.TIMESTAMP(), nullable=True),
        sa.Column('len', sa.Interval(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
